# Add 'beta' label to any PR where the base branch name starts with `beta` or has a `beta` section in the name
beta:
- all:
 - base-branch: ['^beta', 'beta', 'beta*']

# Add 'beta' label to any PR where the base branch name starts with `beta` or has a `beta` section in the name
alpha:
- all:
 - base-branch: ['^alpha', 'alpha', 'alpha*']

# Add 'latest' label to any PR where the base branch name starts with `latest` or has a `latest` section in the name
latest:
- all:
 - base-branch: ['^latest', 'latest', 'latest*']