name: Attach Artifacts
run-name: Attach Artifacts

on:
  release:
    types: [prereleased]
  repository_dispatch:
    types: [attach-artifacts]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag - must not start with v'
        required: true

jobs:
  build:
    name: Attach Artifact
    runs-on: ubuntu-latest

    steps:
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Tag
        id: tag
        uses: JinoArch/get-latest-tag@latest

      - name: Install package
        run: |
          export npm_config_prefix=$(pwd)/package
          npm install -g homebridge-config-ui-x@${{ steps.tag.outputs.latestTag }}

      - name: Remove invalid node-pty node-gyp run
        run: |
          rm -rf $(pwd)/package/lib/node_modules/homebridge-config-ui-x/node_modules/@homebridge/node-pty-prebuilt-multiarch/build

      - name: Create Bundle
        run: |
          tar -C $(pwd)/package --owner=0 --group=0 --format=posix -czvf homebridge-config-ui-x-${{ steps.tag.outputs.latestTag }}.tar.gz .
          shasum -a 256 homebridge-config-ui-x-${{ steps.tag.outputs.latestTag }}.tar.gz > SHASUMS256.txt

      - name: Check Bundle
        run: |
          if [ $(stat -c%s "homebridge-config-ui-x-${{ steps.tag.outputs.latestTag }}.tar.gz") -lt 10000000 ]; then
            echo "Bundle is under 10MB, stopping"
            exit 1
          fi
    
      - name: Upload tar.gz Bundle to GitHub Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: 'homebridge-config-ui-x-${{ steps.tag.outputs.latestTag }}.tar.gz'
          path: |
            ./homebridge-config-ui-x-${{ steps.tag.outputs.latestTag }}.tar.gz
      
    
      - name: Upload SHASUMS256.txt to GitHub Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: 'SHASUMS256.txt'
          path: |
            ./SHASUMS256.txt

      - name: Attach Bundle
        uses: AButler/upload-release-assets@v3.0
        with:
          files: 'homebridge-config-ui-x-${{ steps.tag.outputs.latestTag }}.tar.gz;SHASUMS256.txt'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: ${{ steps.tag.outputs.latestTag }}

      # Sanity check to ensure that release tags don't start with a 'v' version prefix but adhere to the X.Y.Z format
      - name: Check for Tag name Format (github.event.inputs.tag)
        # https://github.com/orgs/community/discussions/25017
        if: startsWith(github.event.inputs.tag, 'v')
        run: |
          echo "Release Tag name must not start with 'v', this was supplied ${{ github.event.inputs.tag }}"
          exit 1

      - name: Install package (github.event.inputs.tag)
        run: |
          export npm_config_prefix=$(pwd)/package
          npm install -g homebridge-config-ui-x@${{ github.event.inputs.tag }}

      - name: Remove invalid node-pty node-gyp run (github.event.inputs.tag)
        run: |
          rm -rf $(pwd)/package/lib/node_modules/homebridge-config-ui-x/node_modules/@homebridge/node-pty-prebuilt-multiarch/build

      - name: Create Bundle (github.event.inputs.tag)
        run: |
          tar -C $(pwd)/package --owner=0 --group=0 --format=posix -czvf homebridge-config-ui-x-${{ github.event.inputs.tag }}.tar.gz .
          shasum -a 256 homebridge-config-ui-x-${{ github.event.inputs.tag }}.tar.gz > SHASUMS256.txt

      - name: Check Bundle (github.event.inputs.tag)
        run: |
          if [ $(stat -c%s "homebridge-config-ui-x-${{ github.event.inputs.tag }}.tar.gz") -lt 10000000 ]; then
            echo "Bundle is under 10MB, stopping"
            exit 1
          fi
    
      - name: Upload tar.gz Bundle to GitHub Artifacts (github.event.inputs.tag)
        uses: actions/upload-artifact@v4
        with:
          name: 'homebridge-config-ui-x-${{ github.event.inputs.tag }}(github.event.inputs.tag).tar.gz'
          path: |
            ./homebridge-config-ui-x-${{ github.event.inputs.tag }}.tar.gz
      
    
      - name: Upload SHASUMS256.txt to GitHub Artifacts (github.event.inputs.tag)
        uses: actions/upload-artifact@v4
        with:
          name: 'SHASUMS256(github.event.inputs.tag).txt'
          path: |
            ./SHASUMS256.txt

      - name: Attach Bundle (github.event.inputs.tag)
        uses: AButler/upload-release-assets@v3.0
        with:
          files: 'homebridge-config-ui-x-${{ github.event.inputs.tag }}.tar.gz;SHASUMS256.txt'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: ${{ github.event.inputs.tag }}

      # Sanity check to ensure that release tags don't start with a 'v' version prefix but adhere to the X.Y.Z format
      - name: Check for Tag name Format (github.ref.tag)
        # https://github.com/orgs/community/discussions/25017
        if: startsWith(github.ref.tag, 'v')
        run: |
          echo "Release Tag name must not start with 'v', this was supplied ${{ github.ref.tag }}"
          exit 1

      - name: Install package (github.ref.tag)
        run: |
          export npm_config_prefix=$(pwd)/package
          npm install -g homebridge-config-ui-x@${{ github.ref.tag }}

      - name: Remove invalid node-pty node-gyp run (github.ref.tag)
        run: |
          rm -rf $(pwd)/package/lib/node_modules/homebridge-config-ui-x/node_modules/@homebridge/node-pty-prebuilt-multiarch/build

      - name: Create Bundle (github.ref.tag)
        run: |
          tar -C $(pwd)/package --owner=0 --group=0 --format=posix -czvf homebridge-config-ui-x-${{ github.ref.tag }}.tar.gz .
          shasum -a 256 homebridge-config-ui-x-${{ github.ref.tag }}.tar.gz > SHASUMS256.txt

      - name: Check Bundle (github.ref.tag)
        run: |
          if [ $(stat -c%s "homebridge-config-ui-x-${{ github.ref.tag }}.tar.gz") -lt 10000000 ]; then
            echo "Bundle is under 10MB, stopping"
            exit 1
          fi
    
      - name: Upload tar.gz Bundle to GitHub Artifacts (github.ref.tag)
        uses: actions/upload-artifact@v4
        with:
          name: 'homebridge-config-ui-x-${{ github.ref.tag }}(github.ref.tag).tar.gz'
          path: |
            ./homebridge-config-ui-x-${{ github.ref.tag }}.tar.gz
      
    
      - name: Upload SHASUMS256.txt to GitHub Artifacts (github.ref.tag)
        uses: actions/upload-artifact@v4
        with:
          name: 'SHASUMS256(github.ref.tag).txt'
          path: |
            ./SHASUMS256.txt

      - name: Attach Bundle (github.ref.tag)
        uses: AButler/upload-release-assets@v3.0
        with:
          files: 'homebridge-config-ui-x-${{ github.ref.tag }}.tar.gz;SHASUMS256.txt'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: ${{ github.ref.tag }}